# yaml-language-server: $schema=https://raw.githubusercontent.com/KevinNitroG/argocd-json-schema/refs/heads/main/schemas/v3.2.2/standalone-strict/v1alpha1applicationset.json
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mimosa-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/AsterisMono/mimosa.git
              revision: $REVISION
              directories:
                - path: apps/*/overlays/$ENV
          - clusters:
              selector:
                matchLabels:
                  env: $ENV
  template:
    metadata:
      name: "{{ .path.basename }}-{{ index .path.segments 1 }}"
    spec:
      project: mimosa-project
      source:
        repoURL: https://github.com/AsterisMono/mimosa.git
        targetRevision: $REVISION
        path: "{{ .path.path }}"
      destination:
        server: "{{ .server }}"
        namespace: "{{ index .path.segments 1 }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
