apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rgarden-tls
spec:
  secretName: rgarden-tls
  commonName: "*.requiem.garden"
  dnsNames:
    - "*.requiem.garden"
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
