---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smb-secrets
  namespace: smb-csi
spec:
  encryptedData:
    password: AgBHDoowEXLSgsM+yY+dlA6ERgCWl0CVvtf9BNGGk3rh/xo5gDScGDzLpG7rrS9gnXL05uv/Pphv9h7tIjyA9pE5HWKB0u+mer2LXnGv6SibaYwdbUNsxWGV8PhC1Zkjm2LL16QBwW8UJEMo4VDWTRTwcX8fkAuNQBk166ZOtiso6d21KVJuSyp5T02WBrTriWilnMm5Myi2/h5HWiO9C7t4rCptVVhx28Qi/HQy9F/XPV2u/FoH8AZuk4FDb4cTzfaanoWDTW9t289S5FCJFLW1ibgJKQhk2Ip3mUU+Gov7ZwmUN+lZioRunbXHQhmNX7A5IiNGPrDx+RyYgPfRx8UXrr2yOFgeBICCNE/mi2uUXAY8Yj3lAUrNWhLzOW0tLBZC9tkelPtKY3EWwewixwbXod8/VWk8kLsG+dpqWQEUwjv7UIzVMUVwg2OXrW95IEN3dKB0oIZ/pw2WsIy14gbG2fJTGDCkZhLDrOoux7JCjRaohai9Q1zwP4l0GHJjn4aj4URQWueTmrEvlBGzF0cJOdtVaLg9X3gVsy5hur6TT+WqQO9MTQ9bBDlu+r+T8NOcSKIwrjvZBRWTuIhACNpjNu2ix0T+c9JpUesAeb7xSmLGwWj6neu4b+KOQ/R7LUvmrz/65W4m4wQTVZfarTHIDnI9xL8EXfrUscPOO88xgntkhN6TGUFNsGFWLwcnVxIo3f9SVSz1xmsKDUy1gwc=
    username: AgAoHL1q/jZDUoXHDXuanyGznCP0LazHWTJgp8M+B+wDhnMlZ0agl+B9LwM32c5h9HdAYs+aXSkAwV34M+XVp5Dcc8pB7UNfRfVDGiOMB6R1TRLxP8A0Dx5Vx1xupq/LRXOTJe7+YTN9/45SIQ7hua86tZO2ecByPcYRLZBxxe0KMMUImJ0nY5x8t3qVLD+AglOAAfoYCFjpzkj55XAMJwdVRMbvv1w9jG5n7BPpv/nMUMPGYj3+3FNU4JrU99CVCeibLVscUnsQ8jCCUEqLqtz08CNrM0VQQLoZf3SwuX+BHIWUWgPtWsGrfxX2yYPn0UlUoOzhIo0WflIxlBbxwiWMp3HVINE1vvejCLAvelFGEM9oIW2brZWNa2zgHgc4cBr/NSHMCxOSacm2CqQgP7vX8wC6nHOdCbUHda0y8NfyQS4YBsU1u9b/ojPfN1q27OYjfPcDqwc9xv9xCwA2OobNm57wCfL+llj5jz06FEP33XPsRwKTjj5OYjo3xE7viZRTHhpr5/PEpai9HmDAG6e3zfE2WyBIqWQiiwLsgV2AvlUqcGS+KsbC1RNmCixJyRWdQKFBbZmPbp6d5CK9kF8mjKtkNApQrVVbCjQuQUnkh46jiEYtGAvyO3oHuiHonNZdJrmykfuCWGfRMN1NPd5d5g/0dunicgOm4sFLuub8IQqOG35TEfzA/ovfyPtkR20Qm59Y4ZB5
  template:
    metadata:
      name: smb-secrets
      namespace: smb-csi
