apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-storage-box
provisioner: smb.csi.k8s.io
parameters:
  source: //u531135.your-storagebox.de/backup
  # if csi.storage.k8s.io/provisioner-secret is provided, will create a sub directory
  # with PV name under source
  csi.storage.k8s.io/provisioner-secret-name: smb-secrets
  csi.storage.k8s.io/provisioner-secret-namespace: smb-csi
  csi.storage.k8s.io/node-stage-secret-name: smb-secrets
  csi.storage.k8s.io/node-stage-secret-namespace: smb-csi
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
