apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich-httproute
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: cilium-gateway
      namespace: gateway-system
  hostnames:
    - "memoria.requiem.garden"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: immich-server
          port: 2283
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
