# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - immich-library-pvc.yaml
  - httproute.yaml
  - postgres.yaml

helmCharts:
  - name: immich
    repo: oci://ghcr.io/immich-app/immich-charts
    releaseName: immich
    namespace: immich
    version: 0.10.3
    valuesFile: values.yaml

namespace: immich
