# yaml-language-server: $schema=https://raw.githubusercontent.com/KevinNitroG/argocd-json-schema/refs/heads/main/schemas/v3.2.2/standalone-strict/v1alpha1appproject.json
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mimosa-infra
spec:
  sourceRepos:
    - "https://github.com/AsterisMono/mimosa"
  destinations:
    - name: "mimosa"
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/KevinNitroG/argocd-json-schema/refs/heads/main/schemas/v3.2.2/standalone-strict/v1alpha1applicationset.json
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mimosa-infra
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/AsterisMono/mimosa.git
        revision: main
        directories:
          - path: kubernetes/infra/*
  template:
    metadata:
      name: "{{ .path.basename }}"
    spec:
      project: mimosa-infra
      source:
        repoURL: https://github.com/AsterisMono/mimosa.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        name: "mimosa"
        namespace: "{{ .path.basename }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
