# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.2-standalone-strict/service.json
apiVersion: v1
kind: Service
metadata:
  name: pds-service
spec:
  selector:
    app.kubernetes.io/name: pds
  ports:
    - protocol: TCP
      port: 3000
      targetPort: http
