apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pds-httproute
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: cilium-gateway
      namespace: gateway-system
  hostnames:
    - "at.requiem.garden"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: pds-service
          port: 3000
          weight: 1
