apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: knot-httproute
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: cilium-gateway
      namespace: gateway-system
  hostnames:
    - "knot.requiem.garden"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: knot-service
          port: 5555
          weight: 1
