---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAzFk0CZSbqHNm4AgrbGJvyQG0CKVk6ZHSj+Un1C/GZMkpUoCEJ0yWRCXsJDIwl/njhUlltixxT7CjMZdf0guUZw0t6mWeDOWckOzhTz6fMaxcgv4+Juk3DCgQ93rli0xgP2vwKKo2ESDvthqQsk3fFqzecghs7+NydO2t6a9WTUswczzPuyGUgZSj5W9RlalcH68VwK+jtls9Vf/fi+w9vaXW8iq2Cro6vYae/F0J0wkZhDIc1jHM5ms1Vy2gLvDZpXbXKIEmLUZlXB8mfhM5rb8Ofa6v8IC/4e+ggGrxRcpowlJKNwYH+l6+6fCLcKF309UY3PEm3Lgenk+QL+g5IIZuEbehTaFW0Qnx8ZuIL/qn88u9JE/TBRBbTm92JYedJ4RhBH2k2L2ZvJ0PZYiSvU0ezXATbLpWRaCZkE3CrEAYlmkBnmWixEKzSsutVw9ZZwgxvAVqvYoMSMEYg+a+o/UFnF1/A2dEieWB4Qw3ngjpxZcwt8ROB1V0PR2uiVLBbpjbzKbR2+LC5Wx8PFK200whnOyNZItCMjXoLJOnxJGSiLDC7MdEb0TvONJ6wQmlCEZXzKGQ0UC8LV3NE2eMyY4KiaTXra0AN1C1vtyKImVWXlAewJd/SLc70Yh8+kzrMrbH5eNimtr1KRQbEMkuIRNT4VOpq/LZLz58JxfA7IjzQbC7KgUvbPvyRO7O0eh8hHuf14wEIi+Myv7hvPg7ZIw==
    client_secret: AgB5w+uukmItkD7vMPBJXlXyrszI1t09ivj5FCa5ssv+o6HekqiiL6Jr5bGiIIS5ao79MeCTqteM1/O4X80Vy9Vy7Yb6caSPZOAfjoCnl49+acEenL+VdIi7j9x8PSuPj5iWOE79TFx2h6y8Bt9V9Ji5vzCJ9MpJSSxNlqZqp07XEsFhGIQmXIDcd0K8eWZfyKwWqqgYvv2882x+5fOD9huLFognFxrIZLEDJHy45QFSLqvgMDdOatKmK04vdvzT2rgylqBfk0zadz0K4EG1Qgp12eoxfok4Xno2LKx5qUOZzBc4BB0+9JSLsQfpYWaneoVrYU4WnecWZwlVszVPOJyWxPTuTgcv50KCZ7t8hs1nmNNORnUYJOkE7HNooUk65IPL0BQPFSTd5iHvkBlxjdphtAiWQnE6LwgiJNEGGVgKuLQExTl/xh/wBbpbeEnoMLjXgGqpayd1h5+F/y+1lEnLBg+mUFoHwsItuO/UNpJbv0t2Kbus6J+NN3PYW49EkFZICMgti8WN9PUx0G35kYO+CgWm09MJNHRyM1RNpkq7zOSwYlW1UhQ5E/mYInCOIakpbnNz6O6RBB8J4KmVBSMEt0UHUitjrbLNbC3N0UyhHUSlDjkqiWQijXSC82WHb7UBScJf0VFkZWk5okhJOo7OpdfJfUwQ359pRLPKAv44Cn0w1M9AyNmcOiSXXI5O2ZGqzi2mVGzm0xfOK5+Q+gwQTOWaZBTqOKck6A6m1uvm3lRDpHXb7B6KDgMpdAKzYCXuanyxhvnDb/yWfC+4bF3J
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
