---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC7Evd+F9CWZiOBfjykSfTzA9LPnsMLwuVG7do644LdA1e3WkAyL721iGNYtHH5AqV6kixkVjULWppdMcqSBANnrad1ztOvXr3xME347/wzp9bd061R9sCNVFXUftVQj8MXdmwjQplCTppx8hbx6e/TU/oo5xATUeJy5phGFqaRrPwcTsHBgSgi1pfuVExGfwZ1b+A3zenBoeISjANXBkPIRpqzAklvv6CyJPMttSqC6/cSfY9i/DcwgSIDDj0Zhav461agEPv5HP3w43FmeSs/CgEFDm0JE9/swT3jWkt4KMtv3Fyyz50KGnVv1cvIAdbe4P/5LA+Vwp0k0nQaqDP9PwDOMEiKQ2oKxy85YhQZk8rYroG3q3K4FGNMDRKVAxE+9ji5fOESt4DUV0B8Gvhr80Ai4JoDOq1cTLpyQurNCnJ1LGMuoMGBFbGwxZhOpla4FtOJwImB8uhtmoCHNdGcyaU0it50HbftDWvIYBxSl9HM3hylMP757MvK/xij1tbw/r3j6kzCAqLDIBfXsOsPvuSiZVRZ6jgbAb5rkjONTjGl0v5fci6r3QctoO4S29QDt8dZHd692fjzH/9rHKLiMNYQsLynMM+YdEvUXHTDzrdwIAO108VdOZY7VtmVDmLAspGltqC06InCFzdWC93LuANx9km5GF48a/mOiDQuFgA+hWNTs8NKowd3WSoNXOHLucJk4GUDsTODSGQmh5BioBCp2zwl9bhy9IiY68Vv0Ss2tuClOLU/
  template:
    metadata:
      name: cloudflare-token-secret
      namespace: cert-manager
