# yaml-language-server: $schema=https://raw.githubusercontent.com/KevinNitroG/argocd-json-schema/refs/heads/main/schemas/v3.0.9/standalone/v1alpha1applicationset.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: 38.0.1
      helm:
        valueFiles:
          - $values/traefik/values.yaml
      chart: traefik
    - repoURL: https://github.com/AsterisMono/mimosa
      targetRevision: HEAD
      ref: values
  destination:
    namespace: traefik
