---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocketid-secrets
  namespace: pocketid
spec:
  encryptedData:
    ENCRYPTION_KEY: AgCHdBMGREXIhTElkp27cVtPUm33+w2tb4EzKxeEOr1qTEUU2GU279tpOd7XC+SR8GMePdayQ8pqgQAXUnAp5+VyrIRqmjxjeTZ4+n9CuzmkjXZHW1PH7Z9rTpGBxaNagZ6Z0XZDCNCy76DUqSkrcdAXuAE+43c5ZIy0VMgGBpyHW5wuwRXkMdkosUDV1BliRSHsnVvCyt15MSpFlmJHLm36jYW2vh47NaFmqMO9uS+3hhjpByModXsj9uQlACwmhmJoK0sW4FVH4CckknSdUte+lSdmks5NdGLCwJB5gmd9Qqf/4pvf4+JLOYPHfVcLeiUIxezDDDWp67XdM6NZqsrn7I+rWsPQx/oKLb2RZ3Ey26Mtrz5GTkbqbQBrAH7WrTi+j+ZjgBvPlHgTvEzK0e4+RrSV5FF2MQcEZy8RsxqTkI0xG9+borpRiYgWEKuPDzEFTUVBHMJ2Ste5dO4EWHnWmw9L+oWTN24D3sqo0fF/PA3gGDpOYnENjuiif0Bt1mOj7gwwuK6tXWUlTY81xx/nzY4KpaMKBbZJ41qlembjh8kknAA3gzMGVFcJKa54FK3pzMQy8NMYBqwL1GFZsHvgzpYIK4Y880v4X930zHLpMyZs+BF3aLA7VwVBv9e+IhBc4sbxYy0310l2QqwDTSAEKQty3LR8Al91yFiZU3E1nUaJpiMbV4rXYvMhBaVzIh+DG2CeqohQoOFMm75wbtTrNzH61oikDzyc+N3MHvDS2HFO8J8ybjcTGB6/qQ==
    MAXMIND_LICENSE_KEY: AgCchZ8z5niWPZQRmwEgBz2zkhLvDp3thm0cAZCeeVkwlF98HFXjQ6f0CtZFeIO+/hftQ3svLJKs1VlWXXtcgP2SGEyR7Sdz/3klzovUQ1TlKTnQUXdQujb3dX48sXg3Qo/Re93cJixPzPKnM67ezP9UnL8n1nGkIfno0pTxr8kV4LiT+MUj2cg+jw6ZDCNZKY8i9vIy1qr+hAm9Lku1ZVRk1BnZEwi4FmUUHSyx/uIVr8AFi8DuWOhHfvB8Cjx9cMLoIV8/8zAFIjoWHiNh3bgq7yjvRO01P/pJ4kCXUpvsP6ANmBuwVi9n9Tf4sP9KhReEJqchBHrWZQ7tMdEX+dR1LfQwUD/A188g5ZJImMRbHajfwQUjMhModdYkw0puQQAAmvGzAzE1sgorWO4vQBmR8ROFCkSTvJ8sbVNl7jUeTb+IhmIZ6TjS4xfugMzA2VsD1ck7I5g7MT2uRPjb0GFql29f7yznKgQGWPl5jNGlI6ROUoSDZCUkKcXZ/emPFJTOrJBv/nof7qd65qL7EUEdtnfiCUdwGBzou40NTWPaEVftsOrNHOiAmviWkJPujN9iVPQObGJCTtEBhIncczwYUwqpIxczpWKhpfVSSK+gfo3bY0COulQFF4Gv8188zROCs2D1qw7K1Cn0Q9t64Gl8vOYhtRfd05ouM/zjo8lAxUFZslvKNuikKoum/wEOMFnJwXr1zJmqYvX+eJK3MT8VaNuaByRlsECKkFZU181ahx8e0P1qjbcm
  template:
    metadata:
      name: pocketid-secrets
      namespace: pocketid
