apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rgarden-tls
  namespace: traefik
spec:
  secretName: rgarden-tls
  commonName: "*.nursery.requiem.garden"
  dnsNames:
    - "*.nursery.requiem.garden"
    - "nursery.requiem.garden"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
